name: Check Visium Python Style
description: Check that the code follows Visium's python style guidelines

inputs:
  python-version:
    required: true
    description: The python version to use for the check

jobs:
  ci:
    using: "composite"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip instll visiumlint
        shell: bash
      
      - name: Overwrite the pyproject.toml if it exists
        run: |
          python -m pip install --upgrade pip
          pip instll visiumlint
        shell: bash

      - name: Check linting with visiumlint
        run: |
          visiumlint
        shell: bash
