name: Check Visium Python Style
description: Check that the code follows Visium's python style guidelines

inputs:
  python-version:
    required: true

jobs:

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.CHECK_PYTHON_STYLE_SSH_PRIVATE_KEY }}'
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev --system --deploy
      shell: bash

    - name: Check linting with visiumlint
      run: |
        visiumlint
      shell: bash

