name: Check Visium Python Style
description: Check that the code follows Visium's python style guidelines

inputs:
  python-version:
    required: true
  path:
    required: false
    default: "./"

jobs:

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install --dev --system --deploy
      shell: bash

    - name: Check linting with visiumlint
      run: |
        visiumlint ${{ inputs.path }}
      shell: bash

