name: Continuous Integration Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-python-style:
    uses: ./.github/workflows/workflow.yml
    #uses: ./workflow.yml
    with:
      python-version: 3.11