name: Continuous Integration Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  check-python-style:
    uses: ./workflow.yml