on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  check-python-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install visiumlint
        shell: bash

      - name: Overwrite the pyproject.toml if it exists
        run: |
          rm -r pyproject.toml
          echo "[tool.black]
          line-length = 120

          [tool.isort]
          profile = \"black\"
          line_length = 120

          [tool.pylint.master]
          load-plugins = \"pylint.extensions.docparams, pylint.extensions.docstyle\"

          [tool.pylint.messages_control]
          disable = \"\"\"fixme,
          too-few-public-methods,\"\"\"

          [tool.pylint.basic]
          variable-rgx = \"^[a-z][a-z0-9_]*$\"
          argument-rgx = \"^[a-z][a-z0-9_]*$\"

          [tool.pylint.format]
          max-line-length = \"120\"

          [tool.pydocstyle]
          add-ignore = \"D107, D104, D103\"
          convention = \"google\"" > pyproject.toml
        shell: bash

      - name: Check linting with visiumlint
        run: |
          visiumlint
          echo "Visium Python Style Check Passed"
        shell: bash
      